$('.btnIrInicio').click(()=>{
    window.location.href="index.php";
})
$('.btnIrNosotros').click(()=>{
    window.location.href="nosotros.php";
})
$('.btnIrNuestoProducto').click(()=>{
    window.location.href="nuestroproducto.php";
})
$('.btnIrReseñas').click(()=>{
    window.location.href="comentarios.php";
})
$('.btnIrContacto').click(()=>{
    window.location.href="contacto.php";
})
$('#btnPresupuesto').click(()=>{
    window.location.href="contacto.php";
})
$('#btnPresupuesto_menu').click(()=>{
    window.location.href="contacto.php";
})
$('.btnMasInformacion').click(()=>{
    window.location.href="nuestroproducto.php";
})